DECLARE
    
    v_QDPEDIDO_QDPEDIDO FA_QVNTS_DPEDIDO.QDPEDIDO_QDPEDIDO%TYPE;
  
BEGIN
	v_QDPEDIDO_QDPEDIDO:=1:
    -- Insertar un nuevo detalle de pedido
    FA_QVNTS_DPEDIDO.INSERTAR_DPEDIDO( 
        QDPEDIDO_QDPEDIDO => v_QDPEDIDO_QDPEDIDO,
        QDPEDIDO_QPEDIDO = 1,
        QDPEDIDO_PRDTO = 2,
        QDPEDIDO_CNTD = 1, 
        QDPEDIDO_PRCIO = 1250000
         );
		DBMS_OUTPUT.PUT_LINE('v_QDPEDIDO_QDPEDIDO-------------------:'||v_QDPEDIDO_QDPEDIDO); 
END;