CREATE OR REPLACE TYPE FA_TY_TO_VNTS_PEDIDO AS OBJECT (
	pedido_clnt INT,
	pedido_fcrea timestamp,
	PEDIDO_PEDIDO INT
    det_pedido FA_TY_TT_VNTS_DPEDIDO
);
CREATE OR REPLACE TYPE FA_TY_TT_VNTS_PEDIDO AS TABLE OF FA_TY_TO_VNTS_PEDIDO;