CREATE OR REPLACE TYPE CL_TY_TO_TRESSPUTA AS OBJECT (
    clnt_clnt CL_TCLNT_CLNT.CLNT_CLNT%TYPE,
    ERROR_MSG   VARCHAR2(500)   -- Mensaje de error
);

CREATE OR REPLACE TYPE CL_TY_TT_TRESSPUTA AS TABLE OF CL_TY_TO_TRESSPUTA;