CREATE OR REPLACE TYPE FA_TY_TO_VNTS_DPEDIDO AS OBJECT (
	DPEDIDO_DPEDIDO          INT ,
    DPEDIDO_PEDIDO           INT,  
    DPEDIDO_PRDTO            INT , 
    DPEDIDO_CNTD             INT  ,
    DPEDIDO_PRCIO            FLOAT,
      
    
);
CREATE OR REPLACE TYPE FA_TY_TT_VNTS_DPEDIDO AS TABLE OF FA_TY_TO_VNTS_DPEDIDO;