CREATE OR REPLACE TYPE FA_TY_TO_PEDIDO_DPEDIDO AS OBJECT (
	PEDIDO_TO FA_TY_TO_VNTS_PEDIDO,
	det_PEDIDO_TO FA_TY_TO_VNTS_DPEDIDO
);
CREATE OR REPLACE TYPE FA_TY_TT_PEDIDO_DPEDIDO AS TABLE OF FA_TY_TO_PEDIDO_DPEDIDO;