CREATE OR REPLACE TYPE FA_TY_TO_VNTS_RPSTA AS OBJECT (
	PEDIDO_CODIGO VARCHAR2(10),
	PEDIDO_MENSAJE VARCHAR2(100),
	PEDIDO_PEDIDO INT
);
CREATE OR REPLACE TYPE FA_TY_TT_VNTS_RPSTA AS TABLE OF FA_TY_TO_VNTS_RPSTA;