CREATE VIEW CL_VCLNT_CLNT AS
SELECT 
    CLNT_CLNT AS ID_CLIENTE,
    CLNT_NOMB AS NOMBRE,
    CLNT_TPID AS TIPO_IDENTIFICACION,
    CLNT_NIT AS NIT,
    CLNT_DIRE AS DIRECCION
FROM 
    CL_TCLNT_CLNT;