CREATE VIEW FA_VVNTS_PEDIDO AS 
SELECT 
            DPEDIDO.DPEDIDO_PEDIDO, 
            DPEDIDO.DPEDIDO_PRDTO,  
            DPEDIDO.DPEDIDO_CNTD,	  
            DPEDIDO.DPEDIDO_PRCIO,  
            DPEDIDO.DPEDIDO_DPEDIDO,
            PEDIDO.PEDIDO_CLNT,    
            PEDIDO.PEDIDO_FCREA   
        FROM 
            FA_TVNTS_PEDIDO PEDIDO
        JOIN 
            FA_TVNTS_DPEDIDO DPEDIDO ON DPEDIDO.DPEDIDO_PEDIDO = PEDIDO.PEDIDO_PEDIDO
        WHERE 
            PEDIDO.PEDIDO_PEDIDO = DPEDIDO.DPEDIDO_PEDIDO;