CREATE SEQUENCE det_pedido_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE OR REPLACE PACKAGE FA_QVNTS_DPEDIDO AS
    -- Insertar un nuevo detalle de pedido
    PROCEDURE insertar_DPEDIDO(
        QDPEDIDO_QDPEDIDO IN FA_TVNTS_DPEDIDO.DPEDIDO_DPEDIDO%TYPE,
        QDPEDIDO_QPEDIDO IN FA_TVNTS_DPEDIDO.DPEDIDO_PEDIDO%TYPE,
        QDPEDIDO_PRDTO IN FA_TVNTS_DPEDIDO.DPEDIDO_PRDTO%TYPE,
        QDPEDIDO_CNTD IN FA_TVNTS_DPEDIDO.DPEDIDO_CNTD%TYPE,
        QDPEDIDO_PRCIO IN FA_TVNTS_DPEDIDO.DPEDIDO_PRCIO%TYPE
    );
    END FA_QVNTS_DPEDIDO;

CREATE OR REPLACE PACKAGE BODY FA_QVNTS_DPEDIDO AS
    -- Insertar un nuevo detalle de pedido
    PROCEDURE insertar_DPEDIDO(
        QDPEDIDO_QDPEDIDO IN FA_TVNTS_DPEDIDO.DPEDIDO_DPEDIDO%TYPE,
        QDPEDIDO_QPEDIDO IN FA_TVNTS_DPEDIDO.DPEDIDO_PEDIDO%TYPE,
        QDPEDIDO_PRDTO IN FA_TVNTS_DPEDIDO.DPEDIDO_PRDTO%TYPE,
        QDPEDIDO_CNTD IN FA_TVNTS_DPEDIDO.DPEDIDO_CNTD%TYPE,
        QDPEDIDO_PRCIO IN FA_TVNTS_DPEDIDO.DPEDIDO_PRCIO%TYPE
    )IS
    BEGIN 
        INSERT INTO FA_TVNTS_DPEDIDO (DPEDIDO_DPEDIDO,DPEDIDO_PEDIDO, DPEDIDO_PRDTO,DPEDIDO_CNTD,DPEDIDO_PRCIO)
        VALUES (det_pedido_seq.nextval,QDPEDIDO_QPEDIDO, QDPEDIDO_PRDTO,QDPEDIDO_CNTD,QDPEDIDO_PRCIO);
        DBMS_OUTPUT.PUT_LINE('Producto insertado correctamente.');
      EXCEPTION
        WHEN OTHERS THEN
            -- En caso de error, hacer rollback y lanzar la excepción
            ROLLBACK;
            RAISE;
    END insertar_DPEDIDO;
END FA_QVNTS_DPEDIDO;

BEGIN
    -- Insertar un nuevo detalle de pedido
    FA_QVNTS_DPEDIDO.INSERTAR_DPEDIDO( 
        QDPEDIDO_QDPEDIDO => 1,
        QDPEDIDO_QPEDIDO => 1,
        QDPEDIDO_PRDTO => 2,
        QDPEDIDO_CNTD => 1, 
        QDPEDIDO_PRCIO => 1250000
         );
END;