CREATE OR REPLACE PACKAGE FA_QVNTS_DPEDIDO AS
    -- Insertar un nuevo detalle de pedido
    PROCEDURE insertar_DPEDIDO(
        QDPEDIDO_QDPEDIDO IN FA_TVNTS_DPEDIDO.DPEDIDO_DPEDIDO%TYPE,
        QDPEDIDO_QPEDIDO IN FA_TVNTS_DPEDIDO.DPEDIDO_PEDIDO%TYPE,
        QDPEDIDO_PRDTO IN FA_TVNTS_DPEDIDO.DPEDIDO_PRDTO%TYPE,
        QDPEDIDO_CNTD IN FA_TVNTS_DPEDIDO.DPEDIDO_CNTD%TYPE,
        QDPEDIDO_PRCIO IN FA_TVNTS_DPEDIDO.DPEDIDO_PRCIO%TYPE
    );
    END FA_QVNTS_DPEDIDO;