CREATE OR REPLACE PACKAGE IN_QPPLR_PRDTO AS
    -- Insertar un nuevo producto
    PROCEDURE insertar_producto(
        QPRDTO_PRDTO IN IN_TPPLR_PRDTO.PRDTO_PRDTO%TYPE,
        QPRDTO_NOMB IN IN_TPPLR_PRDTO.PRDTO_NOMB%TYPE,
        QPRDTO_DESC IN IN_TPPLR_PRDTO.PRDTO_DESC%TYPE,
        QPRDTO_STCK IN IN_TPPLR_PRDTO.PRDTO_STCK%TYPE,
        QPRDTO_PRCIO IN IN_TPPLR_PRDTO.PRDTO_PRCIO%TYPE
    );
    END IN_QPPLR_PRDTO;