CREATE OR REPLACE PACKAGE IN_QPPLR_PRDTO AS
    -- Insertar un nuevo producto
    PROCEDURE insertar_producto(
        QPRDTO_PRDTO IN IN_TPPLR_PRDTO.PRDTO_PRDTO%TYPE,
        QPRDTO_NOMB IN IN_TPPLR_PRDTO.PRDTO_NOMB%TYPE,
        QPRDTO_DESC IN IN_TPPLR_PRDTO.PRDTO_DESC%TYPE,
        QPRDTO_STCK IN IN_TPPLR_PRDTO.PRDTO_STCK%TYPE,
        QPRDTO_PRCIO IN IN_TPPLR_PRDTO.PRDTO_PRCIO%TYPE
    );
    END IN_QPPLR_PRDTO;

CREATE OR REPLACE PACKAGE BODY IN_QPPLR_PRDTO AS
    -- Insertar un nuevo producto
    PROCEDURE insertar_producto(
        QPRDTO_PRDTO IN IN_TPPLR_PRDTO.PRDTO_PRDTO%TYPE,
        QPRDTO_NOMB IN IN_TPPLR_PRDTO.PRDTO_NOMB%TYPE,
        QPRDTO_DESC IN IN_TPPLR_PRDTO.PRDTO_DESC%TYPE,
        QPRDTO_STCK IN IN_TPPLR_PRDTO.PRDTO_STCK%TYPE,
        QPRDTO_PRCIO IN IN_TPPLR_PRDTO.PRDTO_PRCIO%TYPE
    )IS
    BEGIN 
        INSERT INTO IN_TPPLR_PRDTO (PRDTO_PRDTO, PRDTO_NOMB, PRDTO_PRCIO, PRDTO_STCK,PRDTO_DESC)
        VALUES (QPRDTO_PRDTO, QPRDTO_NOMB, QPRDTO_PRCIO, QPRDTO_STCK,QPRDTO_DESC);
        DBMS_OUTPUT.PUT_LINE('Producto insertado correctamente.');
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Error al insertar el producto: ' || SQLERRM);
    END insertar_producto;
END IN_QPPLR_PRDTO;

BEGIN
    -- Insertar un nuevo producto
    gestion_productos.insertar_producto(1, 'Laptop', 120050, 10,'Lapto Hp Ryzen 3');
END;
/