CREATE OR REPLACE TYPE PedidoInfo AS OBJECT (
    PEDIDO_PEDIDO   INT,
    PEDIDO_CLNT     INT,
    PEDIDO_FCREA    TIMESTAMP,
    DPEDIDO_PRDTO   INT,
    DPEDIDO_CNTD    INT,
    DPEDIDO_PRCIO   NUMBER,
    DPEDIDO_DPEDIDO INT
);
/


CREATE OR REPLACE TYPE PedidoInfoTable AS TABLE OF PedidoInfo;
/
