CREATE OR REPLACE TYPE PedidoInfo AS OBJECT (
    PEDIDO_PEDIDO   VARCHAR2(50),
    PEDIDO_CLNT     VARCHAR2(50),
    PEDIDO_FCREA    TIMESTAMP,
    DPEDIDO_PRDTO   INT,
    DPEDIDO_CNTD    INT,
    DPEDIDO_PRCIO   NUMBER,
    DPEDIDO_DPEDIDO VARCHAR2(50)
);
/


CREATE OR REPLACE TYPE PedidoInfoTable AS TABLE OF PedidoInfo;
/
